apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "2001-01-02_15-04-05.999_MST"
      timezone: "Local"
  artifacts:
  - image: cr.yandex/crp2ofrncim33gbrdet7/hello-world
deploy:
  kubectl:
    manifests:
    - pod.yaml
